"""
Deterministic Android project template (template-first generation).

Pure functions, no external dependencies: given a spec dict and a package
name, return a map of {relative_path: file_content} for a minimal but
**buildable** Jetpack Compose / Material 3 app.

Buildability fixes vs. the original inline generator in codegen_worker.py:
- Uses a framework XML theme (android:Theme.Material.Light.NoActionBar), so the
  manifest no longer references a nonexistent @style/Theme.AppCompat.Light with
  no AppCompat dependency.
- Drops the @mipmap/ic_launcher references (no launcher-icon resources were ever
  generated) which previously broke resource linking.
- Emits an empty proguard-rules.pro so the release buildType resolves.
- Lets material3 resolve from the Compose BOM (no pinned-version drift).

The Gradle wrapper JAR is intentionally NOT emitted here. Builds run with a
managed Gradle provided by CI / the build worker (see
.github/workflows/build-generated.yml), which avoids committing a binary jar and
the old recursive-gradlew fallback bug.
"""
from typing import Dict


def generate_project(spec: dict, package_name: str) -> Dict[str, str]:
    """Return {relative_path: content} for a buildable Compose app."""
    package_path = package_name.replace(".", "/")
    app_name = spec.get("app_name", "Generated App")
    description = spec.get("description", "Generated by NL2Build Cloud.")
    min_sdk = int(spec.get("min_sdk", 24))
    target_sdk = int(spec.get("target_sdk", 34))
    compose_compiler = str(spec.get("dependencies", {}).get("compose", "1.5.4"))

    return {
        "settings.gradle.kts": _settings_gradle(app_name),
        "build.gradle.kts": _project_build_gradle(),
        "gradle.properties": _gradle_properties(),
        "gradle/wrapper/gradle-wrapper.properties": _gradle_wrapper_properties(),
        "app/build.gradle.kts": _app_build_gradle(package_name, min_sdk, target_sdk, compose_compiler),
        "app/proguard-rules.pro": "# No custom ProGuard rules.\n",
        "app/src/main/AndroidManifest.xml": _manifest(app_name),
        "app/src/main/res/values/themes.xml": _themes(),
        f"app/src/main/java/{package_path}/MainActivity.kt": _main_activity(package_name),
        f"app/src/main/java/{package_path}/ui/MainScreen.kt": _main_screen(package_name, app_name, description),
    }


def _settings_gradle(app_name: str) -> str:
    root = app_name.replace(" ", "") or "GeneratedApp"
    tpl = """pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "__ROOT__"
include(":app")
"""
    return tpl.replace("__ROOT__", root)


def _project_build_gradle() -> str:
    return """plugins {
    id("com.android.application") version "8.1.4" apply false
    id("org.jetbrains.kotlin.android") version "1.9.20" apply false
}
"""


def _gradle_properties() -> str:
    return """org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
"""


def _gradle_wrapper_properties() -> str:
    # Records the intended Gradle version; CI/build worker provides Gradle 8.2.
    return """distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\\://services.gradle.org/distributions/gradle-8.2-bin.zip
networkTimeout=10000
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
"""


def _app_build_gradle(package_name: str, min_sdk: int, target_sdk: int, compose_compiler: str) -> str:
    tpl = """plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "__PKG__"
    compileSdk = __TARGET__

    defaultConfig {
        applicationId = "__PKG__"
        minSdk = __MIN__
        targetSdk = __TARGET__
        versionCode = 1
        versionName = "1.0"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = "__COMPOSE_COMPILER__"
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

dependencies {
    implementation("androidx.core:core-ktx:1.12.0")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.6.2")
    implementation("androidx.activity:activity-compose:1.8.1")
    implementation(platform("androidx.compose:compose-bom:2023.10.01"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")
}
"""
    return (tpl.replace("__PKG__", package_name)
               .replace("__MIN__", str(min_sdk))
               .replace("__TARGET__", str(target_sdk))
               .replace("__COMPOSE_COMPILER__", compose_compiler))


def _manifest(app_name: str) -> str:
    # No launcher-icon or AppCompat theme references (both broke the build).
    tpl = """<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <application
        android:allowBackup="true"
        android:label="__APP_NAME__"
        android:supportsRtl="true"
        android:theme="@style/Theme.Generated">

        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:theme="@style/Theme.Generated">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
"""
    return tpl.replace("__APP_NAME__", app_name)


def _themes() -> str:
    return """<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="Theme.Generated" parent="android:Theme.Material.Light.NoActionBar" />
</resources>
"""


def _main_activity(package_name: str) -> str:
    tpl = """package __PKG__

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.ui.Modifier
import __PKG__.ui.MainScreen

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MaterialTheme {
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {
                    MainScreen()
                }
            }
        }
    }
}
"""
    return tpl.replace("__PKG__", package_name)


def _main_screen(package_name: str, app_name: str, description: str) -> str:
    safe_desc = description.replace('"', "'").replace("\n", " ")
    tpl = """package __PKG__.ui

import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun MainScreen() {
    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("__APP_NAME__") },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.primaryContainer,
                    titleContentColor = MaterialTheme.colorScheme.onPrimaryContainer
                )
            )
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(16.dp),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.Center
        ) {
            Text(
                text = "__APP_NAME__",
                style = MaterialTheme.typography.headlineLarge,
                textAlign = TextAlign.Center
            )
            Spacer(modifier = Modifier.height(16.dp))
            Text(
                text = "__DESC__",
                style = MaterialTheme.typography.bodyLarge,
                textAlign = TextAlign.Center,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
            Spacer(modifier = Modifier.height(32.dp))
            Button(onClick = { }) {
                Text("Get Started")
            }
        }
    }
}
"""
    return (tpl.replace("__PKG__", package_name)
               .replace("__APP_NAME__", app_name)
               .replace("__DESC__", safe_desc))
